### ISSUE TITLE
Error in astr::format_upasv2_header

### ISSUE THREAD

**Issue by ajaypillarisetti** [accsensors/astr#43]
I've been getting the following error when trying to import UPAS files run in India, where the `GPSUTCOffset` is set to 5.5:

```
Error in dplyr::case_when(!is.na(tz) ~ tz, data$GPSUTCOffset == 0 ~ "UTC",  : 
  Failed to evaluate the right-hand side of formula 3.
Caused by error in `sprintf()`:
! invalid format '%i'; use format %f, %e, %g or %a for numeric objects
```

 From the same location, when this is set to 5, the header import works great. Changing the `%i` to `%f` in the `sprintf` seems to resolve the issue. I believe this problem may occur in other fractional time zones (India is UTC+05:30; Nepal is UTC+05:45).

**Comment by jtryner** [comment]
Ajay,

Thank you for bringing this issue to our attention!  

The update that I just made to the package should resolve this issue.  You might already know this, but, when working with fractional time zones, it's best to enter the `tz` argument in `read_ast_header()` and` read_ast_log()`.  For example, `tz = "Asia/Kolkata"` for UTC+05:30.  If the local time zone in a fractional time zone and you don't enter a character string specifying the tz database time zone as the `tz` argument, then all local timestamps will stay formatted as strings instead of being converted to POSIXct objects. 

Thank you again for helping us improve the astr package!  Please let us know if you have any further issues!

Jessica

**Comment by jtryner** [comment]
Ajay,

Another update here:  We have made additional improvements to the package and in v2.1.1 you no longer need to enter the `tz` argument to get the local timestamps formatted as POSIXct objects when the GPSUTCOffset is fractional.  The package will now identify the correct time zone from a fractional GPSUTCOffset and convert local timestamps to POSIXct objects displayed in that time zone.  

Jessica
